In [2]:
## Data Analysis libraries
import pandas as pd
import numpy as np

## Data Visualization libraries
import matplotlib.pyplot as plt
import seaborn as sns

Q.1. Write a numpy program to find the minimum and maximum value of a given flattened array

Original Array : array([[10, 20],
                        [30, 40]])

In [4]:
## Solution
## org_arr = np.array([[0,1], [2,3]])
## org_arr

org_arr = np.arange(4).reshape(2, 2)
org_arr

array([[0, 1],
       [2, 3]])

In [6]:
## Flatten the array

flat_arr = org_arr.flatten()
flat_arr

array([0, 1, 2, 3])

In [8]:
## Find min and max

print('min_value = ', np.min(flat_arr))
print('max_value = ', np.max(flat_arr))

min_value =  0
max_value =  3


Q2. Q.1. Write a numpy program to find the minimum value index and maximum value index of a given flattened array

Original Array : array([[10, 20],
                        [30, 40]])

In [9]:
org_arr = np.arange(10, 41, 10).reshape(2, 2)
org_arr

array([[10, 20],
       [30, 40]])

In [10]:
flat_arr = org_arr.flatten()
flat_arr

array([10, 20, 30, 40])

In [12]:
print('Index of max value', np.argmax(flat_arr))
print('Index of min value' ,np.argmin(flat_arr))

Index of max value 3
Index of min value 0


### Find the sum of the below array

In [14]:
arr = np.arange(10, 19).reshape(3,3)
arr

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [15]:
## arr.sum()
np.sum(arr)

126

In [16]:
sum(arr)

array([39, 42, 45])

In [18]:
np.sum(arr, axis = 0)

array([39, 42, 45])

In [19]:
np.sum(arr, axis = 1)

array([33, 42, 51])

In [20]:
arr

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

## Find the mean, median, var, std of the below array along both axis 

In [22]:
arr = np.arange(50, 66).reshape(4,4)
arr

array([[50, 51, 52, 53],
       [54, 55, 56, 57],
       [58, 59, 60, 61],
       [62, 63, 64, 65]])

In [23]:
np.mean(arr, axis = 0)

array([56., 57., 58., 59.])

In [24]:
np.mean(arr, axis = 1)

array([51.5, 55.5, 59.5, 63.5])

In [25]:
np.median(arr, axis = 0)

array([56., 57., 58., 59.])

In [26]:
np.median(arr, axis = 1)

array([51.5, 55.5, 59.5, 63.5])

In [27]:
np.var(arr, axis = 1)

array([1.25, 1.25, 1.25, 1.25])

In [28]:
np.var(arr, axis = 0)

array([20., 20., 20., 20.])

In [29]:
np.std(arr, axis = 0)

array([4.47213595, 4.47213595, 4.47213595, 4.47213595])

In [30]:
np.std(arr, axis = 1)

array([1.11803399, 1.11803399, 1.11803399, 1.11803399])

### Indexing and Slicing

In [31]:
arr

array([[50, 51, 52, 53],
       [54, 55, 56, 57],
       [58, 59, 60, 61],
       [62, 63, 64, 65]])

In [32]:
### 60 in the op

arr[2,2]

60

In [33]:
arr[2, 2]

60

In [35]:
## 65 in the output
arr[3, 3]

65

In [36]:
arr[-1, -1]

65

In [37]:
arr

array([[50, 51, 52, 53],
       [54, 55, 56, 57],
       [58, 59, 60, 61],
       [62, 63, 64, 65]])

In [39]:
arr[1:3, 1:3]

array([[55, 56],
       [59, 60]])

In [40]:
arr[2 : 4, 1 : 4]

array([[59, 60, 61],
       [63, 64, 65]])

In [41]:
arr[1 : 4, 2 : 4]

array([[56, 57],
       [60, 61],
       [64, 65]])

In [42]:
arr[1 : 3, 2 : 3]

array([[56],
       [60]])

In [43]:
arr[1 : 4, 2 : 4]

array([[56, 57],
       [60, 61],
       [64, 65]])

In [44]:
arr

array([[50, 51, 52, 53],
       [54, 55, 56, 57],
       [58, 59, 60, 61],
       [62, 63, 64, 65]])

In [45]:
arr[1 : 3, 0: 4]

array([[54, 55, 56, 57],
       [58, 59, 60, 61]])

In [46]:
arr[1 : 3, :]

array([[54, 55, 56, 57],
       [58, 59, 60, 61]])

In [47]:
arr[1 : 3]

array([[54, 55, 56, 57],
       [58, 59, 60, 61]])

In [48]:
arr

array([[50, 51, 52, 53],
       [54, 55, 56, 57],
       [58, 59, 60, 61],
       [62, 63, 64, 65]])

In [50]:
## Reverse the array

arr[:, ::-1]

array([[53, 52, 51, 50],
       [57, 56, 55, 54],
       [61, 60, 59, 58],
       [65, 64, 63, 62]])

In [60]:
li = [50, 51, 52, 53]
li[::-1]

[53, 52, 51, 50]

In [61]:
arr[::-1, :]

array([[62, 63, 64, 65],
       [58, 59, 60, 61],
       [54, 55, 56, 57],
       [50, 51, 52, 53]])

In [62]:
arr

array([[50, 51, 52, 53],
       [54, 55, 56, 57],
       [58, 59, 60, 61],
       [62, 63, 64, 65]])

### Pandas Revisit

In [63]:
import seaborn as sns

sns.get_dataset_names()

['anagrams',
 'anscombe',
 'attention',
 'brain_networks',
 'car_crashes',
 'diamonds',
 'dots',
 'dowjones',
 'exercise',
 'flights',
 'fmri',
 'geyser',
 'glue',
 'healthexp',
 'iris',
 'mpg',
 'penguins',
 'planets',
 'seaice',
 'taxis',
 'tips',
 'titanic']

In [64]:
len(sns.get_dataset_names())

22

In [69]:
data = sns.load_dataset('penguins')
data.head()

species     island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
0  Adelie  Torgersen            39.1           18.7              181.0   
1  Adelie  Torgersen            39.5           17.4              186.0   
2  Adelie  Torgersen            40.3           18.0              195.0   
3  Adelie  Torgersen             NaN            NaN                NaN   
4  Adelie  Torgersen            36.7           19.3              193.0   

   body_mass_g     sex  
0       3750.0    Male  
1       3800.0  Female  
2       3250.0  Female  
3          NaN     NaN  
4       3450.0  Female

In [71]:
## Get the summary of the data

data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 344 entries, 0 to 343
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   species            344 non-null    object 
 1   island             344 non-null    object 
 2   bill_length_mm     342 non-null    float64
 3   bill_depth_mm      342 non-null    float64
 4   flipper_length_mm  342 non-null    float64
 5   body_mass_g        342 non-null    float64
 6   sex                333 non-null    object 
dtypes: float64(4), object(3)
memory usage: 18.9+ KB


In [72]:
## Get the proportion of Male and Female penguins

data['sex'].value_counts(normalize = True)  * 100

Male      50.45045
Female    49.54955
Name: sex, dtype: float64

###  50.45% Male penguins & 49.54% Female penguines

In [73]:
### Get the proportion of species

data['species'].value_counts(normalize = True)  * 100

Adelie       44.186047
Gentoo       36.046512
Chinstrap    19.767442
Name: species, dtype: float64

### Observations:

- 44.18% penguines belong to Adelie species
- 36% belong to Gentoo species
- 19.76% belong to Chinstrap species

In [74]:
## Proportion of penguines per island

data['island'].value_counts(normalize = True)  * 100

Biscoe       48.837209
Dream        36.046512
Torgersen    15.116279
Name: island, dtype: float64

In [76]:
#48.83 % of 344

(48.83 /100) * 344

167.97519999999997

In [77]:
data['island'].value_counts()

Biscoe       168
Dream        124
Torgersen     52
Name: island, dtype: int64

In [78]:
168 + 124 + 52

344

In [79]:
data.head()

species     island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
0  Adelie  Torgersen            39.1           18.7              181.0   
1  Adelie  Torgersen            39.5           17.4              186.0   
2  Adelie  Torgersen            40.3           18.0              195.0   
3  Adelie  Torgersen             NaN            NaN                NaN   
4  Adelie  Torgersen            36.7           19.3              193.0   

   body_mass_g     sex  
0       3750.0    Male  
1       3800.0  Female  
2       3250.0  Female  
3          NaN     NaN  
4       3450.0  Female

In [80]:
## Find the average body mass

data['body_mass_g'].mean()

4201.754385964912

In [81]:
data.shape

(344, 7)

In [82]:
len(data)

344

In [83]:
data.size

2408

In [84]:
344 * 7

2408

In [85]:
arr

array([[50, 51, 52, 53],
       [54, 55, 56, 57],
       [58, 59, 60, 61],
       [62, 63, 64, 65]])

### Array Creation function

In [93]:
arr = np.random.randint(50, 100, 15)
arr

array([95, 59, 70, 72, 66, 52, 92, 98, 92, 93, 63, 72, 64, 74, 79])

In [95]:
## Sort the array

np.sort(arr)

array([52, 59, 63, 64, 66, 70, 72, 72, 74, 79, 92, 92, 93, 95, 98])

In [96]:
arr = np.random.randint(50, 100, 15).reshape(3, 5)
arr

array([[87, 68, 77, 76, 68],
       [92, 98, 98, 55, 88],
       [79, 86, 60, 57, 57]])

In [97]:
## sort the arr

np.sort(arr)    ### default axis is 0

array([[68, 68, 76, 77, 87],
       [55, 88, 92, 98, 98],
       [57, 57, 60, 79, 86]])

In [98]:
np.sort(arr, axis = 1)   ### in sort do not use axis function

array([[68, 68, 76, 77, 87],
       [55, 88, 92, 98, 98],
       [57, 57, 60, 79, 86]])

### np.where()

In [102]:
arr = np.random.randint(50, 100, 15)
arr

array([80, 57, 82, 59, 68, 56, 62, 98, 85, 94, 50, 51, 63, 81, 80])

In [107]:
## if the number in arr is divisible 5 then multiply that number with 10

np.where(arr % 5 == 0, arr, arr * 10)

array([ 80, 570, 820, 590, 680, 560, 620, 980,  85, 940,  50, 510, 630,
       810,  80])

In [106]:
# np.where(condition, on what, what is expectation)