## Common dataset in sklearn library

- Using the sklearn library, datasets can be created manually
- sklearn library allows us to create 2 types of dataset like we can create a regression dataset where the target will be numerical and we can create a classification dataset where the target will be object(categorical)

In [5]:
import pandas as pd
import numpy as np

## Creating a regression dataset from the sklearn library 

In [11]:
from sklearn.datasets import make_regression
X, y = make_regression(n_samples = 5, n_features = 1)

In [12]:
X

array([[ 0.7990175 ],
       [-0.65888536],
       [ 0.56763136],
       [-0.1663113 ],
       [ 0.39740668]])

In [13]:
y

array([ 28.30500033, -23.34085314,  20.10820243,  -5.89153714,
        14.07803483])

## Create a classification dataset

In [24]:
from sklearn.datasets import make_classification
X, y = make_classification(n_samples = 10, n_features = 5, n_informative = 3, n_classes = 2)

In [25]:
X

array([[ 2.13174612e-01, -1.41835773e+00,  1.40095102e+00,
        -1.49837675e+00,  1.03025606e+00],
       [-1.13871908e+00, -1.18962725e+00,  9.40123119e-01,
        -2.43533480e+00, -1.15825518e+00],
       [-1.71773620e-01,  9.24372211e-02, -2.60187671e+00,
         2.92311923e+00,  7.04365580e-01],
       [ 3.95545361e-01, -1.07229256e+00,  9.75685222e-01,
        -7.73450637e-01,  1.18980683e+00],
       [ 6.62146685e-01,  3.17009256e+00, -9.47493986e-01,
         2.00039750e+00, -1.36387030e+00],
       [-9.78301789e-01, -1.19644571e+00,  1.15509107e+00,
        -2.51484536e+00, -9.82075874e-01],
       [ 4.58239745e-03,  2.44918043e-01,  6.13809883e-01,
        -7.18074319e-01, -4.60838098e-01],
       [ 1.42844428e+00,  1.26291946e+00, -3.27712504e-03,
         1.63974935e+00,  1.17636357e+00],
       [-9.16441360e-01,  1.11441489e-01, -1.99853393e+00,
         1.37806501e+00, -7.56203973e-01],
       [ 5.46427729e-01,  1.57788279e+00, -2.38760758e+00,
         3.52564730e+00

In [26]:
y

array([1, 1, 0, 1, 0, 1, 1, 0, 0, 0])

- n_samples = no of rows that you need in your dataset
- n_features = no. of columns that you need in your dataset
- n_classes = since this is a classification dataset that is being created, hence specifying 2 will create 2 classes in the target variable (0, 1)
- n_informative = implies the total useful columns present in the data

In [27]:
from sklearn.datasets import make_classification
X, y = make_classification(n_samples = 10, n_features = 4, n_informative = 2, n_classes = 2)

In [28]:
X

array([[-0.9951824 , -0.13619736,  0.76432087,  0.57692543],
       [-0.0685975 , -1.93242332,  1.15900785, -1.22180708],
       [ 0.62171567,  4.07026565, -2.77016727,  2.25398883],
       [-0.38291341, -2.5178054 ,  1.71243249, -1.39540221],
       [ 1.9440821 ,  0.94584534, -1.88417628, -0.68105883],
       [ 1.58023673, -0.76549691, -0.64884596, -1.5601608 ],
       [-0.90529407, -0.479383  ,  0.89979694,  0.29160407],
       [ 1.90209235, -1.19721078, -0.62233161, -2.05886186],
       [ 0.36709288,  2.0321911 , -1.42215335,  1.08741514],
       [ 0.02259915, -0.17124995,  0.08294291, -0.12747574]])

In [29]:
y

array([1, 1, 0, 1, 0, 1, 1, 0, 0, 1])

In [31]:
import seaborn as sns
sns.get_dataset_names()

['anagrams',
 'anscombe',
 'attention',
 'brain_networks',
 'car_crashes',
 'diamonds',
 'dots',
 'dowjones',
 'exercise',
 'flights',
 'fmri',
 'geyser',
 'glue',
 'healthexp',
 'iris',
 'mpg',
 'penguins',
 'planets',
 'seaice',
 'taxis',
 'tips',
 'titanic']

In [32]:
from sklearn.datasets import load_wine
data = load_wine()
data

{'data': array([[1.423e+01, 1.710e+00, 2.430e+00, ..., 1.040e+00, 3.920e+00,
         1.065e+03],
        [1.320e+01, 1.780e+00, 2.140e+00, ..., 1.050e+00, 3.400e+00,
         1.050e+03],
        [1.316e+01, 2.360e+00, 2.670e+00, ..., 1.030e+00, 3.170e+00,
         1.185e+03],
        ...,
        [1.327e+01, 4.280e+00, 2.260e+00, ..., 5.900e-01, 1.560e+00,
         8.350e+02],
        [1.317e+01, 2.590e+00, 2.370e+00, ..., 6.000e-01, 1.620e+00,
         8.400e+02],
        [1.413e+01, 4.100e+00, 2.740e+00, ..., 6.100e-01, 1.600e+00,
         5.600e+02]]),
 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1

In [33]:
from sklearn.datasets import load_diabetes
data = load_diabetes()

In [34]:
data

{'data': array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
          0.01990749, -0.01764613],
        [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
         -0.06833155, -0.09220405],
        [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
          0.00286131, -0.02593034],
        ...,
        [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
         -0.04688253,  0.01549073],
        [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
          0.04452873, -0.02593034],
        [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
         -0.00422151,  0.00306441]]),
 'target': array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310., 101.,
         69., 179., 185., 118., 171., 166., 144.,  97., 168.,  68.,  49.,
         68., 245., 184., 202., 137.,  85., 131., 283., 129.,  59., 341.,
         87.,  65., 102., 265., 276., 252.,  90., 100.,  55.,  61.,  92.,
        259.,  53., 190., 142.,  75., 142., 155., 225.,  59

In [35]:
from sklearn.datasets import fetch_california_housing
data = fetch_california_housing()
data

{'data': array([[   8.3252    ,   41.        ,    6.98412698, ...,    2.55555556,
           37.88      , -122.23      ],
        [   8.3014    ,   21.        ,    6.23813708, ...,    2.10984183,
           37.86      , -122.22      ],
        [   7.2574    ,   52.        ,    8.28813559, ...,    2.80225989,
           37.85      , -122.24      ],
        ...,
        [   1.7       ,   17.        ,    5.20554273, ...,    2.3256351 ,
           39.43      , -121.22      ],
        [   1.8672    ,   18.        ,    5.32951289, ...,    2.12320917,
           39.43      , -121.32      ],
        [   2.3886    ,   16.        ,    5.25471698, ...,    2.61698113,
           39.37      , -121.24      ]]),
 'target': array([4.526, 3.585, 3.521, ..., 0.923, 0.847, 0.894]),
 'frame': None,
 'target_names': ['MedHouseVal'],
 'feature_names': ['MedInc',
  'HouseAge',
  'AveRooms',
  'AveBedrms',
  'Population',
  'AveOccup',
  'Latitude',
  'Longitude'],
 'DESCR': '.. _california_housing_dataset:\n