In [1]:
## Data Analysis libraries

import pandas as pd
import numpy as np

## Data Visualization libraries
import matplotlib.pyplot as plt
import seaborn as sns

## NumPy Quiz Q3.

In [2]:
np.array([25, 35.75, 48, 59, 73, 'Python'])

array(['25', '35.75', '48', '59', '73', 'Python'], dtype='<U32')

### Creating 2 D arrays

In [3]:
li = [[10, 20, 30, 40], [50, 60, 70, 80]]
li

[[10, 20, 30, 40], [50, 60, 70, 80]]

In [4]:
arr1 = np.array(li)
arr1

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [6]:
arr1.ndim    ## ndim means no of dimensions

2

In [7]:
l2 = [[1,2,3], [4,5,6], [7,8,9]]
l2

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [8]:
arr2 = np.array(l2)
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Method 1 : Creating a 2D array from a 1D array

In [9]:
## Step 1 : Create a 1 Dimensional array
## Step 2 : Apply some function on the 1D array to convert it into 2D array
## Step 3 : Display and verify the 2D array

In [15]:
arr3 = np.arange(10, 22)
arr3

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21])

In [16]:
arr3.ndim

1

In [19]:
## Reshape function to convert 1D array into 2D array
## <array_name>.reshape(total_rows, total columns)

arr3_reshaped = arr3.reshape(4, 3)
arr3_reshaped

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21]])

In [20]:
arr3_reshaped.ndim

2

### Method 2 : Creating a 2D array from a 1D array

In [33]:
## Step 1 : Create a 1 Dimensional array
## Step 2 : Apply some function on the 1D array to convert it into 2D array
## Step 3 : Display and verify the 2D array

In [34]:
arr5 = np.arange(50, 66)
arr5

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65])

In [35]:
arr5.ndim

1

In [45]:
## Use Resize function

arr5_resized = np.resize(arr5, (4, 4))
arr5_resized

array([[50, 51, 52, 53],
       [54, 55, 56, 57],
       [58, 59, 60, 61],
       [62, 63, 64, 65]])

#### Note: Reshape and Resize are used to convert 1D array into 2D array

### Method 1 :  Create a 1D array from a 2D array

In [22]:
## Step 1 : Create a 2D array
## Step 2 : Apply some function to convert a 2D array into 1D array
## Step 3 : Display the 1D array and verify

In [21]:
arr4 = np.arange(3,15).reshape(4,3)
arr4

array([[ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [26]:
## Flatten function to convert 2D array into 1D array

arr4_flattened = arr4.flatten()
arr4_flattened

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [27]:
arr4_flattened.ndim

1

### Method 2 : Converting a 2D array into 1D array

In [28]:
## Step 1 : Create a 2D array
## Step 2 : Apply some function to convert 2D array into 1D array
## Step 3 : Display and verify the 1D array

In [29]:
arr4 = np.arange(3, 15).reshape(4, 3)
arr4

array([[ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [30]:
arr4.ndim

2

In [31]:
## Apply Ravel Function for converting 2D array to 1D array

arr4_raveled = arr4.ravel()
arr4_raveled

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [32]:
arr4_raveled.ndim

1

#### Note : Flatten and Ravel functions are used for converting a 2D array into 1D array

## Swap Rows and Columns of a 2D array

In [46]:
arr6 = np.arange(9).reshape(3, 3)
arr6

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [47]:
arr6.T

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

## Concatenating the arrays

In [48]:
arr7 = np.array([1, 2, 3])
arr8 = np.array([4,5,6])
print(arr7)
print(arr8)

[1 2 3]
[4 5 6]


In [50]:
np.concatenate([arr7, arr8])

array([1, 2, 3, 4, 5, 6])

In [51]:
arr9 = np.array([[7, 8], [9, 10]])
arr9

array([[ 7,  8],
       [ 9, 10]])

In [52]:
arr10 = np.array([[11, 12], [13, 14]])
arr10

array([[11, 12],
       [13, 14]])

In [53]:
np.concatenate([arr9, arr10])

array([[ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14]])

In [54]:
np.concatenate([arr9, arr10], axis = 1)

array([[ 7,  8, 11, 12],
       [ 9, 10, 13, 14]])

### Splitting the arrays

In [59]:
arr11 = np.array([10, 20, 30, 40, 50, 60, 70, 80])
arr11

array([10, 20, 30, 40, 50, 60, 70, 80])

In [56]:
np.split(arr11, 3)

[array([10, 20, 30]), array([40, 50, 60]), array([70, 80, 90])]

In [60]:
np.split(arr11, 2)

[array([10, 20, 30, 40]), array([50, 60, 70, 80])]

In [61]:
np.split(arr11, 4)

[array([10, 20]), array([30, 40]), array([50, 60]), array([70, 80])]

### Concatenating using hstack and vstack

In [62]:
arr9

array([[ 7,  8],
       [ 9, 10]])

In [63]:
arr10

array([[11, 12],
       [13, 14]])

In [64]:
np.concatenate([arr9, arr10], axis = 0)

array([[ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14]])

In [66]:
np.vstack([arr9, arr10])

array([[ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14]])

In [67]:
np.concatenate([arr9, arr10], axis = 1)

array([[ 7,  8, 11, 12],
       [ 9, 10, 13, 14]])

In [68]:
np.hstack([arr9, arr10])

array([[ 7,  8, 11, 12],
       [ 9, 10, 13, 14]])

### Assignment 1 : Can you try vsplit() and hsplit()
### Assignment 2 : Difference between reshape() and resize() 
### Assignment 3 : Difference between flatten() and ravel()


### Indexing and Slicing a 2 D array

In [70]:
arr = np.arange(10, 22).reshape(4, 3)
arr

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21]])

In [73]:
arr[1][1]

14

In [74]:
arr[1, 1]

14

In [75]:
arr[2, 2]

18

In [76]:
### arr[ 1 : 2+1 , 1 : 2 + 1 ]

arr[1:3, 1:3]

array([[14, 15],
       [17, 18]])

In [77]:
arr[2:4, 1:3]

array([[17, 18],
       [20, 21]])

In [78]:
arr[2:4, 0:3]

array([[16, 17, 18],
       [19, 20, 21]])

In [79]:
arr[2:4, :]

array([[16, 17, 18],
       [19, 20, 21]])

In [80]:
arr[0:4, 1:3]

array([[11, 12],
       [14, 15],
       [17, 18],
       [20, 21]])

In [81]:
arr[:, 1:]

array([[11, 12],
       [14, 15],
       [17, 18],
       [20, 21]])