In [6]:
## Data Analysis libraries

import pandas as pd
import numpy as np

## Data Visualization libraries

import matplotlib.pyplot as plt
import seaborn as sns

## Warning library import 
import warnings
warnings.filterwarnings('ignore')

## Reading the dataset 

In [4]:
data = pd.read_csv('Salaries.csv')
data.head()

Id       EmployeeName                                        JobTitle  \
0   1     NATHANIEL FORD  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY   
1   2       GARY JIMENEZ                 CAPTAIN III (POLICE DEPARTMENT)   
2   3     ALBERT PARDINI                 CAPTAIN III (POLICE DEPARTMENT)   
3   4  CHRISTOPHER CHONG            WIRE ROPE CABLE MAINTENANCE MECHANIC   
4   5    PATRICK GARDNER    DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)   

     BasePay OvertimePay   OtherPay Benefits   TotalPay  TotalPayBenefits  \
0  167411.18         0.0  400184.25      NaN  567595.43         567595.43   
1  155966.02   245131.88  137811.38      NaN  538909.28         538909.28   
2  212739.13   106088.18    16452.6      NaN  335279.91         335279.91   
3    77916.0    56120.71   198306.9      NaN  332343.61         332343.61   
4   134401.6      9737.0  182234.59      NaN  326373.19         326373.19   

   Year  Notes         Agency Status  
0  2011    NaN  San Francisco    NaN  
1  2011    NaN  San Francisco    NaN  
2  2011    NaN  San Francisco    NaN  
3  2011    NaN  San Francisco    NaN  
4  2011    NaN  San Francisco    NaN

### Data Quality Issues

1. NaN values in Status, Notes & Benefits
2. Drop Duplicate rows
3. Verify Column Data Types
4. Employee Name and JobTitle fix the value of the column
5. Round the pay columns
6. Replace Id with EmployeeID
7. TotalPay and TotalPayBenefits seems to duplicate columns

### Replace Id with EmployeeId

In [10]:
dic = {
    'Id' : 'EmployeeId'
}
dic

{'Id': 'EmployeeId'}

In [20]:
data = data.rename(dic, axis = 1)
data.head()

EmployeeId       EmployeeName  \
0           1     NATHANIEL FORD   
1           2       GARY JIMENEZ   
2           3     ALBERT PARDINI   
3           4  CHRISTOPHER CHONG   
4           5    PATRICK GARDNER   

                                         JobTitle    BasePay OvertimePay  \
0  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY  167411.18         0.0   
1                 CAPTAIN III (POLICE DEPARTMENT)  155966.02   245131.88   
2                 CAPTAIN III (POLICE DEPARTMENT)  212739.13   106088.18   
3            WIRE ROPE CABLE MAINTENANCE MECHANIC    77916.0    56120.71   
4    DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)   134401.6      9737.0   

    OtherPay Benefits   TotalPay  TotalPayBenefits  Year  Notes  \
0  400184.25      NaN  567595.43         567595.43  2011    NaN   
1  137811.38      NaN  538909.28         538909.28  2011    NaN   
2    16452.6      NaN  335279.91         335279.91  2011    NaN   
3   198306.9      NaN  332343.61         332343.61  2011    NaN   
4  182234.59      NaN  326373.19         326373.19  2011    NaN   

          Agency Status  
0  San Francisco    NaN  
1  San Francisco    NaN  
2  San Francisco    NaN  
3  San Francisco    NaN  
4  San Francisco    NaN

### Verify Column data types

In [21]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 148654 entries, 0 to 148653
Data columns (total 13 columns):
 #   Column            Non-Null Count   Dtype  
---  ------            --------------   -----  
 0   EmployeeId        148654 non-null  int64  
 1   EmployeeName      148654 non-null  object 
 2   JobTitle          148654 non-null  object 
 3   BasePay           148049 non-null  object 
 4   OvertimePay       148654 non-null  object 
 5   OtherPay          148654 non-null  object 
 6   Benefits          112495 non-null  object 
 7   TotalPay          148654 non-null  float64
 8   TotalPayBenefits  148654 non-null  float64
 9   Year              148654 non-null  int64  
 10  Notes             0 non-null       float64
 11  Agency            148654 non-null  object 
 12  Status            38119 non-null   object 
dtypes: float64(3), int64(2), object(8)
memory usage: 15.9+ MB


#### Observations:

1. The data contains 1,48,654 rows(i.e. 1,48,654 employee details)
2. Total columns in data is 13
3. Notes is 0 non null(100% missing values in Notes columns)
4. Status column also has a lot of missing values hence delete Status
5. BasePay, OvertimePay, otherpay, Benefits are object but they should be float columns. Changing the data type of these columns is necessary.

### Drop Status and Notes column from the data

In [22]:
cols_to_drop = ['Status', 'Notes']
cols_to_drop

['Status', 'Notes']

In [23]:
data = data.drop(cols_to_drop, axis = 1)
data.head()

EmployeeId       EmployeeName  \
0           1     NATHANIEL FORD   
1           2       GARY JIMENEZ   
2           3     ALBERT PARDINI   
3           4  CHRISTOPHER CHONG   
4           5    PATRICK GARDNER   

                                         JobTitle    BasePay OvertimePay  \
0  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY  167411.18         0.0   
1                 CAPTAIN III (POLICE DEPARTMENT)  155966.02   245131.88   
2                 CAPTAIN III (POLICE DEPARTMENT)  212739.13   106088.18   
3            WIRE ROPE CABLE MAINTENANCE MECHANIC    77916.0    56120.71   
4    DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)   134401.6      9737.0   

    OtherPay Benefits   TotalPay  TotalPayBenefits  Year         Agency  
0  400184.25      NaN  567595.43         567595.43  2011  San Francisco  
1  137811.38      NaN  538909.28         538909.28  2011  San Francisco  
2    16452.6      NaN  335279.91         335279.91  2011  San Francisco  
3   198306.9      NaN  332343.61         332343.61  2011  San Francisco  
4  182234.59      NaN  326373.19         326373.19  2011  San Francisco

### Changing the data type of BasePay, OtherPay, Benefits, OvertimePay

In [24]:
data['BasePay'].unique()

array([167411.18, 155966.02, 212739.13, ..., '6.04', '15.5',
       'Not Provided'], dtype=object)

In [29]:
data['OvertimePay'].unique()

array([0.0, 245131.88, 106088.18, ..., '102.7', '56.77', 'Not Provided'],
      dtype=object)

In [30]:
data['OtherPay'].unique()

array([400184.25, 137811.38, 16452.6, ..., '13.35', 'Not Provided',
       '-618.13'], dtype=object)

In [31]:
data['Benefits'].unique()

array([nan, 44430.12, 69810.19, ..., '0.13', '1.24', 'Not Provided'],
      dtype=object)

### Converting Base Pay column to float

### If we try to directly convert BasePay to float, Pandas  astype does not allow us to convert, becasue we have a string value "Not Provided" inside the BasePay column

In [32]:
data['BasePay'] = data['BasePay'].astype('float')

ValueError: could not convert string to float: 'Not Provided'

In [33]:
### Step 1 : Replace Not provided with nan(missing value)
### Step 2 : Convert the column to float type

In [36]:
dic1 = {
    'Not Provided' : np.nan
}
dic1

{'Not Provided': nan}

In [37]:
### Step 1 : Replace Not provided with nan(missing value)

data['BasePay'] = data['BasePay'].replace(dic1)
data['BasePay'].unique()

array([167411.18, 155966.02, 212739.13, ..., '17.26', '6.04', '15.5'],
      dtype=object)

In [38]:
### Step 2 : Convert the column to float type

data['BasePay'] = data['BasePay'].astype('float')
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 148654 entries, 0 to 148653
Data columns (total 11 columns):
 #   Column            Non-Null Count   Dtype  
---  ------            --------------   -----  
 0   EmployeeId        148654 non-null  int64  
 1   EmployeeName      148654 non-null  object 
 2   JobTitle          148654 non-null  object 
 3   BasePay           148045 non-null  float64
 4   OvertimePay       148654 non-null  object 
 5   OtherPay          148654 non-null  object 
 6   Benefits          112495 non-null  object 
 7   TotalPay          148654 non-null  float64
 8   TotalPayBenefits  148654 non-null  float64
 9   Year              148654 non-null  int64  
 10  Agency            148654 non-null  object 
dtypes: float64(3), int64(2), object(6)
memory usage: 13.6+ MB


### Convert the OvertimePay column to float

In [40]:
### Step 1 : Replace Not provided with nan(missing value)
### Step 2 : Convert the column to float type

In [41]:
dic1

{'Not Provided': nan}

In [42]:
data['OvertimePay'] = data['OvertimePay'].replace(dic1)
data['OvertimePay'].unique()

array([0.0, 245131.88, 106088.18, ..., '102.7', '56.77', nan],
      dtype=object)

In [43]:
data['OvertimePay'] = data['OvertimePay'].astype('float')
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 148654 entries, 0 to 148653
Data columns (total 11 columns):
 #   Column            Non-Null Count   Dtype  
---  ------            --------------   -----  
 0   EmployeeId        148654 non-null  int64  
 1   EmployeeName      148654 non-null  object 
 2   JobTitle          148654 non-null  object 
 3   BasePay           148045 non-null  float64
 4   OvertimePay       148650 non-null  float64
 5   OtherPay          148654 non-null  object 
 6   Benefits          112495 non-null  object 
 7   TotalPay          148654 non-null  float64
 8   TotalPayBenefits  148654 non-null  float64
 9   Year              148654 non-null  int64  
 10  Agency            148654 non-null  object 
dtypes: float64(4), int64(2), object(5)
memory usage: 13.6+ MB


### Convert OtherPay and Benefits to float

In [44]:
dic1

{'Not Provided': nan}

In [46]:
data[['OtherPay', 'Benefits']] = data[['OtherPay', 'Benefits']].replace(dic1)
data['OtherPay'].unique()

array([400184.25, 137811.38, 16452.6, ..., '13.35', nan, '-618.13'],
      dtype=object)

In [47]:
data['Benefits'].unique()

array([nan, 44430.12, 69810.19, ..., '0.16', '0.13', '1.24'], dtype=object)

In [48]:
data[['OtherPay', 'Benefits']] = data[['OtherPay', 'Benefits']].astype('float')
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 148654 entries, 0 to 148653
Data columns (total 11 columns):
 #   Column            Non-Null Count   Dtype  
---  ------            --------------   -----  
 0   EmployeeId        148654 non-null  int64  
 1   EmployeeName      148654 non-null  object 
 2   JobTitle          148654 non-null  object 
 3   BasePay           148045 non-null  float64
 4   OvertimePay       148650 non-null  float64
 5   OtherPay          148650 non-null  float64
 6   Benefits          112491 non-null  float64
 7   TotalPay          148654 non-null  float64
 8   TotalPayBenefits  148654 non-null  float64
 9   Year              148654 non-null  int64  
 10  Agency            148654 non-null  object 
dtypes: float64(6), int64(2), object(3)
memory usage: 13.6+ MB


### Round off all the floating columns to 2 decimal places

In [49]:
data.head()

EmployeeId       EmployeeName  \
0           1     NATHANIEL FORD   
1           2       GARY JIMENEZ   
2           3     ALBERT PARDINI   
3           4  CHRISTOPHER CHONG   
4           5    PATRICK GARDNER   

                                         JobTitle    BasePay  OvertimePay  \
0  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY  167411.18         0.00   
1                 CAPTAIN III (POLICE DEPARTMENT)  155966.02    245131.88   
2                 CAPTAIN III (POLICE DEPARTMENT)  212739.13    106088.18   
3            WIRE ROPE CABLE MAINTENANCE MECHANIC   77916.00     56120.71   
4    DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)  134401.60      9737.00   

    OtherPay  Benefits   TotalPay  TotalPayBenefits  Year         Agency  
0  400184.25       NaN  567595.43         567595.43  2011  San Francisco  
1  137811.38       NaN  538909.28         538909.28  2011  San Francisco  
2   16452.60       NaN  335279.91         335279.91  2011  San Francisco  
3  198306.90       NaN  332343.61         332343.61  2011  San Francisco  
4  182234.59       NaN  326373.19         326373.19  2011  San Francisco

### Method 1 : 

In [50]:
float_cols = ['BasePay', 'OvertimePay', 'OtherPay', 'Benefits', 'TotalPay', 'TotalPayBenefits']
float_cols

['BasePay',
 'OvertimePay',
 'OtherPay',
 'Benefits',
 'TotalPay',
 'TotalPayBenefits']

In [52]:
data[float_cols] = round(data[float_cols], 2)
data.head()

EmployeeId       EmployeeName  \
0           1     NATHANIEL FORD   
1           2       GARY JIMENEZ   
2           3     ALBERT PARDINI   
3           4  CHRISTOPHER CHONG   
4           5    PATRICK GARDNER   

                                         JobTitle    BasePay  OvertimePay  \
0  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY  167411.18         0.00   
1                 CAPTAIN III (POLICE DEPARTMENT)  155966.02    245131.88   
2                 CAPTAIN III (POLICE DEPARTMENT)  212739.13    106088.18   
3            WIRE ROPE CABLE MAINTENANCE MECHANIC   77916.00     56120.71   
4    DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)  134401.60      9737.00   

    OtherPay  Benefits   TotalPay  TotalPayBenefits  Year         Agency  
0  400184.25       NaN  567595.43         567595.43  2011  San Francisco  
1  137811.38       NaN  538909.28         538909.28  2011  San Francisco  
2   16452.60       NaN  335279.91         335279.91  2011  San Francisco  
3  198306.90       NaN  332343.61         332343.61  2011  San Francisco  
4  182234.59       NaN  326373.19         326373.19  2011  San Francisco

### Method 2:

In [61]:
## decimal_cols = data.select_dtypes('float').columns.to_list()
## decimal_cols

In [58]:
decimal_cols = data.select_dtypes('float')
decimal_cols = decimal_cols.columns.to_list()
decimal_cols

['BasePay',
 'OvertimePay',
 'OtherPay',
 'Benefits',
 'TotalPay',
 'TotalPayBenefits']

In [59]:
data[decimal_cols] = round(data[decimal_cols], 2)
data.head()

EmployeeId       EmployeeName  \
0           1     NATHANIEL FORD   
1           2       GARY JIMENEZ   
2           3     ALBERT PARDINI   
3           4  CHRISTOPHER CHONG   
4           5    PATRICK GARDNER   

                                         JobTitle    BasePay  OvertimePay  \
0  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY  167411.18         0.00   
1                 CAPTAIN III (POLICE DEPARTMENT)  155966.02    245131.88   
2                 CAPTAIN III (POLICE DEPARTMENT)  212739.13    106088.18   
3            WIRE ROPE CABLE MAINTENANCE MECHANIC   77916.00     56120.71   
4    DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)  134401.60      9737.00   

    OtherPay  Benefits   TotalPay  TotalPayBenefits  Year         Agency  
0  400184.25       NaN  567595.43         567595.43  2011  San Francisco  
1  137811.38       NaN  538909.28         538909.28  2011  San Francisco  
2   16452.60       NaN  335279.91         335279.91  2011  San Francisco  
3  198306.90       NaN  332343.61         332343.61  2011  San Francisco  
4  182234.59       NaN  326373.19         326373.19  2011  San Francisco

### Fix EmployeeName & JobTitle

In [63]:
data['EmployeeName'] = data['EmployeeName'].str.title()
data.head()

EmployeeId       EmployeeName  \
0           1     Nathaniel Ford   
1           2       Gary Jimenez   
2           3     Albert Pardini   
3           4  Christopher Chong   
4           5    Patrick Gardner   

                                         JobTitle    BasePay  OvertimePay  \
0  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY  167411.18         0.00   
1                 CAPTAIN III (POLICE DEPARTMENT)  155966.02    245131.88   
2                 CAPTAIN III (POLICE DEPARTMENT)  212739.13    106088.18   
3            WIRE ROPE CABLE MAINTENANCE MECHANIC   77916.00     56120.71   
4    DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)  134401.60      9737.00   

    OtherPay  Benefits   TotalPay  TotalPayBenefits  Year         Agency  
0  400184.25       NaN  567595.43         567595.43  2011  San Francisco  
1  137811.38       NaN  538909.28         538909.28  2011  San Francisco  
2   16452.60       NaN  335279.91         335279.91  2011  San Francisco  
3  198306.90       NaN  332343.61         332343.61  2011  San Francisco  
4  182234.59       NaN  326373.19         326373.19  2011  San Francisco

In [65]:
data['JobTitle'] = data['JobTitle'].str.capitalize()
data.head()

EmployeeId       EmployeeName  \
0           1     Nathaniel Ford   
1           2       Gary Jimenez   
2           3     Albert Pardini   
3           4  Christopher Chong   
4           5    Patrick Gardner   

                                         JobTitle    BasePay  OvertimePay  \
0  General manager-metropolitan transit authority  167411.18         0.00   
1                 Captain iii (police department)  155966.02    245131.88   
2                 Captain iii (police department)  212739.13    106088.18   
3            Wire rope cable maintenance mechanic   77916.00     56120.71   
4    Deputy chief of department,(fire department)  134401.60      9737.00   

    OtherPay  Benefits   TotalPay  TotalPayBenefits  Year         Agency  
0  400184.25       NaN  567595.43         567595.43  2011  San Francisco  
1  137811.38       NaN  538909.28         538909.28  2011  San Francisco  
2   16452.60       NaN  335279.91         335279.91  2011  San Francisco  
3  198306.90       NaN  332343.61         332343.61  2011  San Francisco  
4  182234.59       NaN  326373.19         326373.19  2011  San Francisco

### Set the Employee Id column as a row index column

In [69]:
data = data.set_index('EmployeeId')
data.head()

EmployeeName                                        JobTitle  \
EmployeeId                                                                      
1              Nathaniel Ford  General manager-metropolitan transit authority   
2                Gary Jimenez                 Captain iii (police department)   
3              Albert Pardini                 Captain iii (police department)   
4           Christopher Chong            Wire rope cable maintenance mechanic   
5             Patrick Gardner    Deputy chief of department,(fire department)   

              BasePay  OvertimePay   OtherPay  Benefits   TotalPay  \
EmployeeId                                                           
1           167411.18         0.00  400184.25       NaN  567595.43   
2           155966.02    245131.88  137811.38       NaN  538909.28   
3           212739.13    106088.18   16452.60       NaN  335279.91   
4            77916.00     56120.71  198306.90       NaN  332343.61   
5           134401.60      9737.00  182234.59       NaN  326373.19   

            TotalPayBenefits  Year         Agency  
EmployeeId                                         
1                  567595.43  2011  San Francisco  
2                  538909.28  2011  San Francisco  
3                  335279.91  2011  San Francisco  
4                  332343.61  2011  San Francisco  
5                  326373.19  2011  San Francisco

### Explore the dataset

In [71]:
data.head()

EmployeeName                                        JobTitle  \
EmployeeId                                                                      
1              Nathaniel Ford  General manager-metropolitan transit authority   
2                Gary Jimenez                 Captain iii (police department)   
3              Albert Pardini                 Captain iii (police department)   
4           Christopher Chong            Wire rope cable maintenance mechanic   
5             Patrick Gardner    Deputy chief of department,(fire department)   

              BasePay  OvertimePay   OtherPay  Benefits   TotalPay  \
EmployeeId                                                           
1           167411.18         0.00  400184.25       NaN  567595.43   
2           155966.02    245131.88  137811.38       NaN  538909.28   
3           212739.13    106088.18   16452.60       NaN  335279.91   
4            77916.00     56120.71  198306.90       NaN  332343.61   
5           134401.60      9737.00  182234.59       NaN  326373.19   

            TotalPayBenefits  Year         Agency  
EmployeeId                                         
1                  567595.43  2011  San Francisco  
2                  538909.28  2011  San Francisco  
3                  335279.91  2011  San Francisco  
4                  332343.61  2011  San Francisco  
5                  326373.19  2011  San Francisco

In [72]:
data['TotalPay'].mean()

74768.32197169267

In [73]:
data['TotalPay'].median()

71426.60999999999

### Sort the value of TotalPay column in ascending order

In [75]:
data.sort_values('TotalPay')

EmployeeName  \
EmployeeId                          
148654                  Joe Lopez   
106746            Tiffany M Rasso   
106747           Bertha  Robinson   
106748           Kermith T Miller   
106749      Rita I Sinasohn-Pharr   
...                           ...   
36160              Gary Altenberg   
110533                 Amy P Hart   
110532                David Shinn   
2                    Gary Jimenez   
1                  Nathaniel Ford   

                                                  JobTitle    BasePay  \
EmployeeId                                                              
148654                          Counselor, log cabin ranch       0.00   
106746                                 Recreation director        NaN   
106747                                    Transit operator        NaN   
106748                                     Utility plumber        NaN   
106749                                        Clerk typist        NaN   
...                                                    ...        ...   
36160                         Lieutenant, fire suppression  128808.87   
110533                                   Asst med examiner  318835.49   
110532                                      Deputy chief 3  129150.01   
2                          Captain iii (police department)  155966.02   
1           General manager-metropolitan transit authority  167411.18   

            OvertimePay   OtherPay  Benefits   TotalPay  TotalPayBenefits  \
EmployeeId                                                                  
148654             0.00    -618.13      0.00    -618.13           -618.13   
106746             0.00       0.00   7959.18       0.00           7959.18   
106747             0.00       0.00   7959.18       0.00           7959.18   
106748             0.00       0.00   7959.18       0.00           7959.18   
106749             0.00       0.00   7959.18       0.00           7959.18   
...                 ...        ...       ...        ...               ...   
36160         220909.48   13126.31  44430.12  362844.66         407274.78   
110533         10712.95   60563.54  89540.23  390111.98         479652.21   
110532             0.00  342802.63  38780.04  471952.64         510732.68   
2             245131.88  137811.38       NaN  538909.28         538909.28   
1                  0.00  400184.25       NaN  567595.43         567595.43   

            Year         Agency  
EmployeeId                       
148654      2014  San Francisco  
106746      2013  San Francisco  
106747      2013  San Francisco  
106748      2013  San Francisco  
106749      2013  San Francisco  
...          ...            ...  
36160       2012  San Francisco  
110533      2014  San Francisco  
110532      2014  San Francisco  
2           2011  San Francisco  
1           2011  San Francisco  

[148654 rows x 10 columns]

### Sort the data in descending order

In [78]:
data.sort_values('TotalPay', ascending = False)

EmployeeName  \
EmployeeId                       
1               Nathaniel Ford   
2                 Gary Jimenez   
110532             David Shinn   
110533              Amy P Hart   
36160           Gary Altenberg   
...                        ...   
106782         Su-Wen  Mcmanus   
106781      Kimberly F Johnson   
106780       Jack L Brodnax Jr   
106779           Ronald R Orge   
148654               Joe Lopez   

                                                  JobTitle    BasePay  \
EmployeeId                                                              
1           General manager-metropolitan transit authority  167411.18   
2                          Captain iii (police department)  155966.02   
110532                                      Deputy chief 3  129150.01   
110533                                   Asst med examiner  318835.49   
36160                         Lieutenant, fire suppression  128808.87   
...                                                    ...        ...   
106782                                         Secretary 2        NaN   
106781                                    Transit operator        NaN   
106780                         Junior management assistant        NaN   
106779                             Parking control officer        NaN   
148654                          Counselor, log cabin ranch       0.00   

            OvertimePay   OtherPay  Benefits   TotalPay  TotalPayBenefits  \
EmployeeId                                                                  
1                  0.00  400184.25       NaN  567595.43         567595.43   
2             245131.88  137811.38       NaN  538909.28         538909.28   
110532             0.00  342802.63  38780.04  471952.64         510732.68   
110533         10712.95   60563.54  89540.23  390111.98         479652.21   
36160         220909.48   13126.31  44430.12  362844.66         407274.78   
...                 ...        ...       ...        ...               ...   
106782             0.00       0.00   7959.18       0.00           7959.18   
106781             0.00       0.00   7959.18       0.00           7959.18   
106780             0.00       0.00   7959.18       0.00           7959.18   
106779             0.00       0.00   7959.18       0.00           7959.18   
148654             0.00    -618.13      0.00    -618.13           -618.13   

            Year         Agency  
EmployeeId                       
1           2011  San Francisco  
2           2011  San Francisco  
110532      2014  San Francisco  
110533      2014  San Francisco  
36160       2012  San Francisco  
...          ...            ...  
106782      2013  San Francisco  
106781      2013  San Francisco  
106780      2013  San Francisco  
106779      2013  San Francisco  
148654      2014  San Francisco  

[148654 rows x 10 columns]